### ISSUE TITLE
LVGL support

### ISSUE THREAD

**Issue by sam0910** [nspsck/RM67162_Micropython_QSPI#12]
I think this is the only repo on github, RM67162 for micropython.
Thank you so much for it.

Is there anyway to make this driver support LVGL?

**Comment by nspsck** [comment]
Hi!

> Thank you so much for it.

You are welcome!

> Is there anyway to make this driver support LVGL?

If your display is through spi and you do not use an ESP32S2, S3, C3, or C6, you can get it up and running by modifying a few commands for the st7789 driver provided by LVGL. If you want it to work for this specific board provided by Lilygo, it gets complicated quickly. You have to modify the QSPI protocol either by making it treated as an SPI protocol (extremely tedious and hard) or extending the existing SPI protocol to support QSPI, which can be simpler if you choose to let it lose the SPI compatibility and only serve this Display. Otherwise, it's again, very tedious and hard.

But even if you manage to implement all these, if you were using the Lilygo boards, LVGL won't compile anyway because the S3 is not supported yet.

**Comment by sam0910** [comment]
Thank you so much for the reply :)
Recently LVGL team is not able to keep up with the dev pace of micropython.
It seems their development priorities are not in micropython.

I found interesting repo [kdschlosser/lvgl_micropython](https://github.com/kdschlosser/lvgl_micropython).
He made the LVGL as a user C module of micropython, it supports ESP32-S3.
I thought there is possibility to use it :)

The QSPI is the matter, thank you for the solution.
